[project]
name = "leaflets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "easyocr>=1.7.2",
    "jupyter>=1.1.1",
    "loguru>=0.7.2",
    "openai>=1.57.4",
    "pandas>=2.2.3",
    "pillow>=10.4.0",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.2",
    "tqdm>=4.66.5",
    "transformers>=4.47.0",
    "ultralytics>=8.3.9",
]
