model_path: "yolo11l-seg.pt"
data_path: "data/data-seg.yaml"
epochs: 30
batch: 16
imgsz: 640
cache: true

hsv_h: 0.05
hsv_s: 0.3
hsv_v: 0.1
degrees: 2.0
translate: 0.1
scale: 0.05
shear: 1.0
fliplr: 0.0
